// ============================================
//  GEODOR FASHION — Product Catalog
//  Replace placeholder data with real products
// ============================================

const PRODUCTS = [
  {
    id: 1,
    name: "Eclipse Structured Coat",
    category: "avant-garde",
    categoryLabel: "Avant-Garde",
    price: 485,
    originalPrice: null,
    badge: "new",
    description: "An architectural marvel in heavyweight wool. The asymmetric lapel and oversized shoulder construction make a statement before you say a word. Lined in silk satin.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["#1a1a1a","#2d2420","#3d3530"],
    colorNames: ["Obsidian","Espresso","Ash Umber"],
    images: ["images/women_1.jpeg","images/women_2.jpeg","images/women_3.jpeg"],
    imagePlaceholder: "Eclipse Coat · Avant-Garde",
    material: "82% Wool, 18% Cashmere. Silk satin lining.",
    care: "Dry clean only."
  },
  {
    id: 2,
    name: "Nomad Utility Jacket",
    category: "streetwear",
    categoryLabel: "Streetwear",
    price: 295,
    originalPrice: 380,
    badge: "sale",
    description: "Tactical meets minimal. Multi-pocket nylon shell with a hidden hood and adjustable hem. The uniform of the urban explorer.",
    sizes: ["S","M","L","XL","XXL"],
    colors: ["#4a5240","#2a2a2a","#8b7355"],
    colorNames: ["Sage Ops","Matte Black","Desert Tan"],
    images: ["images/women_4.jpeg"],
    imagePlaceholder: "Nomad Jacket · Streetwear",
    material: "100% Recycled Nylon Shell.",
    care: "Machine wash cold, hang dry."
  },
  {
    id: 3,
    name: "Bias-Cut Silk Slip Dress",
    category: "minimalist",
    categoryLabel: "Minimalist",
    price: 320,
    originalPrice: null,
    badge: null,
    description: "Pure seduction in motion. Cut on the bias for a liquid drape that moves with your body. Available in three considered colorways.",
    sizes: ["XS","S","M","L"],
    colors: ["#c8b89a","#1a1a2e","#8b2635"],
    colorNames: ["Sand Dune","Midnight","Crimson"],
    images: ["images/women_5.jpeg"],
    imagePlaceholder: "Silk Slip Dress · Minimalist",
    material: "100% Silk Charmeuse.",
    care: "Hand wash cold or dry clean."
  },
  {
    id: 4,
    name: "Hand-Draped Couture Gown",
    category: "couture",
    categoryLabel: "Couture",
    price: 1850,
    originalPrice: null,
    badge: "new",
    description: "Atelier-crafted. Each piece is hand-draped and finished by a single master tailor. No two are identical. Allow 4–6 weeks for creation.",
    sizes: ["Custom"],
    colors: ["#f5f0eb","#c9a84c","#1a1a1a"],
    colorNames: ["Ivory","Gold Leaf","Noir"],
    images: ["images/product-4-a.jpg"],
    imagePlaceholder: "Couture Gown · Atelier",
    material: "French Duchess Satin. Hand-beaded embellishments.",
    care: "Dry clean only. Professional care recommended."
  },
  {
    id: 5,
    name: "Deconstructed Linen Blazer",
    category: "avant-garde",
    categoryLabel: "Avant-Garde",
    price: 395,
    originalPrice: null,
    badge: null,
    description: "Tailoring that refuses to conform. Exposed seams, raw edges, and a deliberately unfinished hem. Structure through deliberate unstructuring.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["#d4cbb8","#5c5248","#2a2420"],
    colorNames: ["Natural Linen","Tobacco","Dark Walnut"],
    images: ["images/product-5-a.jpg"],
    imagePlaceholder: "Linen Blazer · Avant-Garde",
    material: "100% Stone-washed Belgian Linen.",
    care: "Machine wash gentle, lay flat to dry."
  },
  {
    id: 6,
    name: "Fluid Wide-Leg Trousers",
    category: "minimalist",
    categoryLabel: "Minimalist",
    price: 215,
    originalPrice: null,
    badge: null,
    description: "Movement as design. Crafted from a weightless crepe that creates a perfect silhouette whether you stand or walk.",
    sizes: ["XS","S","M","L","XL"],
    colors: ["#1a1a1a","#c8c4bc","#2d4a3e"],
    colorNames: ["Noir","Dove","Forest"],
    images: ["images/product-6-a.jpg"],
    imagePlaceholder: "Wide-Leg Trousers · Minimalist",
    material: "68% Viscose, 32% Polyester Crepe.",
    care: "Hand wash cold or dry clean."
  },
  {
    id: 7,
    name: "Cargo Oversized Hoodie",
    category: "streetwear",
    categoryLabel: "Streetwear",
    price: 165,
    originalPrice: null,
    badge: "new",
    description: "The ultimate off-duty essential. Heavyweight French terry with a dropped shoulder and kangaroo pocket large enough to mean it.",
    sizes: ["S","M","L","XL","XXL"],
    colors: ["#3a3a3a","#6b5c4e","#2a3a2a"],
    colorNames: ["Graphite","Clay","Forest Night"],
    images: ["images/product-7-a.jpg"],
    imagePlaceholder: "Cargo Hoodie · Streetwear",
    material: "100% Organic Cotton French Terry.",
    care: "Machine wash warm, tumble dry low."
  },
  {
    id: 8,
    name: "Crystal-Pleated Midi Skirt",
    category: "couture",
    categoryLabel: "Couture",
    price: 680,
    originalPrice: null,
    badge: null,
    description: "Pleats set by hand using a traditional Japanese technique. The silk organza catches light with every movement, creating a luminous halo effect.",
    sizes: ["XS","S","M","L"],
    colors: ["#e8ddd0","#c9a84c","#8b6b8b"],
    colorNames: ["Pearl","Gold Dust","Amethyst"],
    images: ["images/product-8-a.jpg"],
    imagePlaceholder: "Crystal Pleat Skirt · Couture",
    material: "100% Silk Organza. Hand-pressed pleats.",
    care: "Dry clean only."
  }
];

// Export for use across files
window.PRODUCTS = PRODUCTS;
